#!/bin/sh
DIR="$HOME/Pictures/Screenshots"
mkdir -p "$DIR"
FILE="$DIR/$(date +%T_%F)'_zoneshot.png'"
grim -g "$(slurp)" "$FILE" && wl-copy --type image/png < "$FILE" 
notify-send 'Screenshot' 'zone screenshot in default dir'
